services:

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      # - POSTGRES_USER=chalk
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data

  
  # chalk:
  #   container_name: chalk
  #   command: "chalk --config /etc/chalk/config/config.yaml --migrations /etc/chalk/migrations"
  #   image: chalk:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./config/:/etc/chalk/config/
  #   depends_on:
  #     - postgres
  #     - redis
  
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: halgiventude
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data


volumes:
  postgres_data:
  redis_data:
  minio_data: